# Chats with openAI models, sends curriculum and gets back a list of questions and answers pairs.

import json
import os

import openai

openai.api_key = os.getenv("OPENAI_API_KEY")


# return the responses as a json array with question and answer pairs.
_SYSTEM_PROMPT = """
You are a helpful assistant that generates questions and answers for a given curriculum.

The curriculum is a list of topics, each with a name and a description.

The questions and answers should be in the style of a multiple choice question.

The questions should be in the style of a question that a student would ask in a classroom.

Here is an example of the curriculum:



Here is an example of the questions and answers generated by the model:

{questions_and_answers}

```json
[
    {
        "question": "Name a prime number between 11 and 20",
        "answers": ["11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
        "correct_answers": ["13"]
    }
]
```

"""

_USER_PROMPT = """
Curriculum: {curriculum}
"""


def get_questions_and_answers(curriculum):
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": _USER_PROMPT.format(curriculum=curriculum)},
        ],
    )
    return extract_json_from_response(response.choices[0].message.content)


def extract_json_from_response(response):
    # find the json object in the response
    json_str = response.split("```json")[1].split("```")[0]
    return json.loads(json_str)
